import { FunctionComponent, useCallback, useState } from "react";
import Table from "react-bootstrap/Table";
import styles from './styles.module.css'
import { TableRow } from "../TableRow/TableRow";
import logo from "../../assets/logo.webp"

const demonArr: Array<[string, number, string, string, number]> =
    [
        [
            "Herald",
            91,
            "Seraph",
            "/megaten-fusion-tool/smt4/demons/Seraph",
            0
        ],
        [
            "Herald",
            83,
            "Metatron",
            "/megaten-fusion-tool/smt4/demons/Metatron",
            1
        ],
        [
            "Herald",
            75,
            "Mastema",
            "/megaten-fusion-tool/smt4/demons/Mastema",
            2
        ],
        [
            "Herald",
            71,
            "Aniel",
            "/megaten-fusion-tool/smt4/demons/Aniel",
            3
        ],
        [
            "Herald",
            67,
            "Sraosha",
            "/megaten-fusion-tool/smt4/demons/Sraosha",
            4
        ],
        [
            "Herald",
            62,
            "Azrael",
            "/megaten-fusion-tool/smt4/demons/Azrael",
            5
        ],
        [
            "Herald",
            57,
            "Kazfiel",
            "/megaten-fusion-tool/smt4/demons/Kazfiel",
            6
        ],
        [
            "Herald",
            45,
            "Israfel",
            "/megaten-fusion-tool/smt4/demons/Israfel",
            7
        ],
        [
            "Herald",
            40,
            "Victor",
            "/megaten-fusion-tool/smt4/demons/Victor",
            8
        ],
        [
            "Herald",
            35,
            "Lailah",
            "/megaten-fusion-tool/smt4/demons/Lailah",
            9
        ],
        [
            "Megami",
            82,
            "Lakshmi",
            "/megaten-fusion-tool/smt4/demons/Lakshmi",
            10
        ],
        [
            "Megami",
            76,
            "Norn",
            "/megaten-fusion-tool/smt4/demons/Norn",
            11
        ],
        [
            "Megami",
            69,
            "Izanami",
            "/megaten-fusion-tool/smt4/demons/Izanami",
            12
        ],
        [
            "Megami",
            63,
            "Anat",
            "/megaten-fusion-tool/smt4/demons/Anat",
            13
        ],
        [
            "Megami",
            57,
            "Tlazolteotl",
            "/megaten-fusion-tool/smt4/demons/Tlazolteotl",
            14
        ],
        [
            "Megami",
            51,
            "Pallas Athena",
            "/megaten-fusion-tool/smt4/demons/Pallas%20Athena",
            15
        ],
        [
            "Megami",
            45,
            "Ishtar",
            "/megaten-fusion-tool/smt4/demons/Ishtar",
            16
        ],
        [
            "Megami",
            39,
            "Scathach",
            "/megaten-fusion-tool/smt4/demons/Scathach",
            17
        ],
        [
            "Megami",
            33,
            "Brigid",
            "/megaten-fusion-tool/smt4/demons/Brigid",
            18
        ],
        [
            "Megami",
            25,
            "Parvati",
            "/megaten-fusion-tool/smt4/demons/Parvati",
            19
        ],
        [
            "Megami",
            18,
            "Hathor",
            "/megaten-fusion-tool/smt4/demons/Hathor",
            20
        ],
        [
            "Megami",
            11,
            "Fortuna",
            "/megaten-fusion-tool/smt4/demons/Fortuna",
            21
        ],
        [
            "Avian",
            71,
            "Garuda",
            "/megaten-fusion-tool/smt4/demons/Garuda",
            22
        ],
        [
            "Avian",
            62,
            "Yatagarasu",
            "/megaten-fusion-tool/smt4/demons/Yatagarasu",
            23
        ],
        [
            "Avian",
            52,
            "Feng Huang",
            "/megaten-fusion-tool/smt4/demons/Feng%20Huang",
            24
        ],
        [
            "Avian",
            42,
            "Thunderbird",
            "/megaten-fusion-tool/smt4/demons/Thunderbird",
            25
        ],
        [
            "Avian",
            33,
            "Vidofnir",
            "/megaten-fusion-tool/smt4/demons/Vidofnir",
            26
        ],
        [
            "Avian",
            25,
            "Phoenix",
            "/megaten-fusion-tool/smt4/demons/Phoenix",
            27
        ],
        [
            "Avian",
            15,
            "Suparna",
            "/megaten-fusion-tool/smt4/demons/Suparna",
            28
        ],
        [
            "Avian",
            3,
            "Hamsa",
            "/megaten-fusion-tool/smt4/demons/Hamsa",
            29
        ],
        [
            "Tree",
            64,
            "Yggdrasil",
            "/megaten-fusion-tool/smt4/demons/Yggdrasil",
            30
        ],
        [
            "Tree",
            55,
            "Haoma",
            "/megaten-fusion-tool/smt4/demons/Haoma",
            31
        ],
        [
            "Tree",
            44,
            "Kukunochi",
            "/megaten-fusion-tool/smt4/demons/Kukunochi",
            32
        ],
        [
            "Tree",
            35,
            "Mayahuel",
            "/megaten-fusion-tool/smt4/demons/Mayahuel",
            33
        ],
        [
            "Tree",
            28,
            "Narcissus",
            "/megaten-fusion-tool/smt4/demons/Narcissus",
            34
        ],
        [
            "Tree",
            19,
            "Daphne",
            "/megaten-fusion-tool/smt4/demons/Daphne",
            35
        ],
        [
            "Divine",
            71,
            "Cherub",
            "/megaten-fusion-tool/smt4/demons/Cherub",
            36
        ],
        [
            "Divine",
            62,
            "Throne",
            "/megaten-fusion-tool/smt4/demons/Throne",
            37
        ],
        [
            "Divine",
            51,
            "Dominion",
            "/megaten-fusion-tool/smt4/demons/Dominion",
            38
        ],
        [
            "Divine",
            41,
            "Virtue",
            "/megaten-fusion-tool/smt4/demons/Virtue",
            39
        ],
        [
            "Divine",
            33,
            "Power",
            "/megaten-fusion-tool/smt4/demons/Power",
            40
        ],
        [
            "Divine",
            26,
            "Principality",
            "/megaten-fusion-tool/smt4/demons/Principality",
            41
        ],
        [
            "Divine",
            18,
            "Archangel",
            "/megaten-fusion-tool/smt4/demons/Archangel",
            42
        ],
        [
            "Divine",
            3,
            "Angel",
            "/megaten-fusion-tool/smt4/demons/Angel",
            43
        ],
        [
            "Flight",
            57,
            "Da Peng",
            "/megaten-fusion-tool/smt4/demons/Da%20Peng",
            44
        ],
        [
            "Flight",
            51,
            "Rukh",
            "/megaten-fusion-tool/smt4/demons/Rukh",
            45
        ],
        [
            "Flight",
            29,
            "Tuofei",
            "/megaten-fusion-tool/smt4/demons/Tuofei",
            46
        ],
        [
            "Flight",
            23,
            "Caladrius",
            "/megaten-fusion-tool/smt4/demons/Caladrius",
            47
        ],
        [
            "Flight",
            16,
            "Gu Huo Niao",
            "/megaten-fusion-tool/smt4/demons/Gu%20Huo%20Niao",
            48
        ],
        [
            "Flight",
            9,
            "Harpy",
            "/megaten-fusion-tool/smt4/demons/Harpy",
            49
        ],
        [
            "Flight",
            2,
            "Tangata Manu",
            "/megaten-fusion-tool/smt4/demons/Tangata%20Manu",
            50
        ],
        [
            "Yoma",
            70,
            "Ganesha",
            "/megaten-fusion-tool/smt4/demons/Ganesha",
            51
        ],
        [
            "Yoma",
            61,
            "Master Therion",
            "/megaten-fusion-tool/smt4/demons/Master%20Therion",
            52
        ],
        [
            "Yoma",
            54,
            "Xiuhtecuhtli",
            "/megaten-fusion-tool/smt4/demons/Xiuhtecuhtli",
            53
        ],
        [
            "Yoma",
            45,
            "Valkyrie",
            "/megaten-fusion-tool/smt4/demons/Valkyrie",
            54
        ],
        [
            "Yoma",
            38,
            "Shiwanna",
            "/megaten-fusion-tool/smt4/demons/Shiwanna",
            55
        ],
        [
            "Yoma",
            30,
            "Dis",
            "/megaten-fusion-tool/smt4/demons/Dis",
            56
        ],
        [
            "Yoma",
            24,
            "Karasu Tengu",
            "/megaten-fusion-tool/smt4/demons/Karasu%20Tengu",
            57
        ],
        [
            "Yoma",
            18,
            "Koppa Tengu",
            "/megaten-fusion-tool/smt4/demons/Koppa%20Tengu",
            58
        ],
        [
            "Yoma",
            12,
            "Agathion",
            "/megaten-fusion-tool/smt4/demons/Agathion",
            59
        ],
        [
            "Yoma",
            6,
            "Vodyanik",
            "/megaten-fusion-tool/smt4/demons/Vodyanik",
            60
        ],
        [
            "Yoma",
            1,
            "Centaur",
            "/megaten-fusion-tool/smt4/demons/Centaur",
            61
        ],
        [
            "Nymph",
            59,
            "Peri",
            "/megaten-fusion-tool/smt4/demons/Peri",
            62
        ],
        [
            "Nymph",
            48,
            "Sarasvati",
            "/megaten-fusion-tool/smt4/demons/Sarasvati",
            63
        ],
        [
            "Nymph",
            36,
            "Kikuri-Hime",
            "/megaten-fusion-tool/smt4/demons/Kikuri-Hime",
            64
        ],
        [
            "Nymph",
            25,
            "Senri",
            "/megaten-fusion-tool/smt4/demons/Senri",
            65
        ],
        [
            "Nymph",
            8,
            "Apsaras",
            "/megaten-fusion-tool/smt4/demons/Apsaras",
            66
        ],
        [
            "Vile",
            95,
            "Demiurge",
            "/megaten-fusion-tool/smt4/demons/Demiurge",
            67
        ],
        [
            "Vile",
            85,
            "Seth",
            "/megaten-fusion-tool/smt4/demons/Seth",
            68
        ],
        [
            "Vile",
            80,
            "Yaso Magatsuhi",
            "/megaten-fusion-tool/smt4/demons/Yaso%20Magatsuhi",
            69
        ],
        [
            "Vile",
            73,
            "Pales",
            "/megaten-fusion-tool/smt4/demons/Pales",
            70
        ],
        [
            "Vile",
            66,
            "Alciel",
            "/megaten-fusion-tool/smt4/demons/Alciel",
            71
        ],
        [
            "Vile",
            58,
            "Taotie",
            "/megaten-fusion-tool/smt4/demons/Taotie",
            72
        ],
        [
            "Vile",
            51,
            "Pachacamac",
            "/megaten-fusion-tool/smt4/demons/Pachacamac",
            73
        ],
        [
            "Vile",
            37,
            "Mishaguji",
            "/megaten-fusion-tool/smt4/demons/Mishaguji",
            74
        ],
        [
            "Vile",
            26,
            "Baphomet",
            "/megaten-fusion-tool/smt4/demons/Baphomet",
            75
        ],
        [
            "Raptor",
            70,
            "Hresvelgr",
            "/megaten-fusion-tool/smt4/demons/Hresvelgr",
            76
        ],
        [
            "Raptor",
            64,
            "Huoniao",
            "/megaten-fusion-tool/smt4/demons/Huoniao",
            77
        ],
        [
            "Raptor",
            53,
            "Anzu",
            "/megaten-fusion-tool/smt4/demons/Anzu",
            78
        ],
        [
            "Raptor",
            43,
            "Gurr",
            "/megaten-fusion-tool/smt4/demons/Gurr",
            79
        ],
        [
            "Raptor",
            31,
            "Zhen",
            "/megaten-fusion-tool/smt4/demons/Zhen",
            80
        ],
        [
            "Raptor",
            23,
            "Itsumade",
            "/megaten-fusion-tool/smt4/demons/Itsumade",
            81
        ],
        [
            "Raptor",
            17,
            "Moh Shuvuu",
            "/megaten-fusion-tool/smt4/demons/Moh%20Shuvuu",
            82
        ],
        [
            "Raptor",
            9,
            "Camazotz",
            "/megaten-fusion-tool/smt4/demons/Camazotz",
            83
        ],
        [
            "Raptor",
            1,
            "Fuxi",
            "/megaten-fusion-tool/smt4/demons/Fuxi",
            84
        ],
        [
            "Wood",
            61,
            "Erlkonig",
            "/megaten-fusion-tool/smt4/demons/Erlkonig",
            85
        ],
        [
            "Wood",
            51,
            "Alraune",
            "/megaten-fusion-tool/smt4/demons/Alraune",
            86
        ],
        [
            "Wood",
            42,
            "Zaccoum",
            "/megaten-fusion-tool/smt4/demons/Zaccoum",
            87
        ],
        [
            "Wood",
            29,
            "Skogsra",
            "/megaten-fusion-tool/smt4/demons/Skogsra",
            88
        ],
        [
            "Wood",
            22,
            "Mandrake",
            "/megaten-fusion-tool/smt4/demons/Mandrake",
            89
        ],
        [
            "Wood",
            14,
            "Shan Xiao",
            "/megaten-fusion-tool/smt4/demons/Shan%20Xiao",
            90
        ],
        [
            "Deity",
            88,
            "Vishnu",
            "/megaten-fusion-tool/smt4/demons/Vishnu",
            91
        ],
        [
            "Deity",
            80,
            "Hachiman",
            "/megaten-fusion-tool/smt4/demons/Hachiman",
            92
        ],
        [
            "Deity",
            75,
            "Apsu",
            "/megaten-fusion-tool/smt4/demons/Apsu",
            93
        ],
        [
            "Deity",
            70,
            "Baal",
            "/megaten-fusion-tool/smt4/demons/Baal",
            94
        ],
        [
            "Deity",
            69,
            "Mahamayuri",
            "/megaten-fusion-tool/smt4/demons/Mahamayuri",
            95
        ],
        [
            "Deity",
            65,
            "Odin",
            "/megaten-fusion-tool/smt4/demons/Odin",
            96
        ],
        [
            "Deity",
            59,
            "Ometeotl",
            "/megaten-fusion-tool/smt4/demons/Ometeotl",
            97
        ],
        [
            "Deity",
            53,
            "Osiris",
            "/megaten-fusion-tool/smt4/demons/Osiris",
            98
        ],
        [
            "Deity",
            48,
            "Lord Nandou",
            "/megaten-fusion-tool/smt4/demons/Lord%20Nandou",
            99
        ],
        [
            "Deity",
            41,
            "Prometheus",
            "/megaten-fusion-tool/smt4/demons/Prometheus",
            100
        ],
        [
            "Deity",
            35,
            "Inti",
            "/megaten-fusion-tool/smt4/demons/Inti",
            101
        ],
        [
            "Deity",
            30,
            "Thoth",
            "/megaten-fusion-tool/smt4/demons/Thoth",
            102
        ],
        [
            "Avatar",
            69,
            "Barong",
            "/megaten-fusion-tool/smt4/demons/Barong",
            103
        ],
        [
            "Avatar",
            61,
            "Anubis",
            "/megaten-fusion-tool/smt4/demons/Anubis",
            104
        ],
        [
            "Avatar",
            53,
            "Ukano Mitama",
            "/megaten-fusion-tool/smt4/demons/Ukano%20Mitama",
            105
        ],
        [
            "Avatar",
            47,
            "Chimera",
            "/megaten-fusion-tool/smt4/demons/Chimera",
            106
        ],
        [
            "Avatar",
            41,
            "Kaiming Shou",
            "/megaten-fusion-tool/smt4/demons/Kaiming%20Shou",
            107
        ],
        [
            "Avatar",
            32,
            "Makami",
            "/megaten-fusion-tool/smt4/demons/Makami",
            108
        ],
        [
            "Avatar",
            24,
            "Kamapua'a",
            "/megaten-fusion-tool/smt4/demons/Kamapua'a",
            109
        ],
        [
            "Avatar",
            14,
            "Shiisaa",
            "/megaten-fusion-tool/smt4/demons/Shiisaa",
            110
        ],
        [
            "Holy",
            70,
            "Sphinx",
            "/megaten-fusion-tool/smt4/demons/Sphinx",
            111
        ],
        [
            "Holy",
            60,
            "Sleipnir",
            "/megaten-fusion-tool/smt4/demons/Sleipnir",
            112
        ],
        [
            "Holy",
            52,
            "Baihu",
            "/megaten-fusion-tool/smt4/demons/Baihu",
            113
        ],
        [
            "Holy",
            45,
            "Airavata",
            "/megaten-fusion-tool/smt4/demons/Airavata",
            114
        ],
        [
            "Holy",
            33,
            "Qing Niugai",
            "/megaten-fusion-tool/smt4/demons/Qing%20Niugai",
            115
        ],
        [
            "Holy",
            26,
            "Pabilsag",
            "/megaten-fusion-tool/smt4/demons/Pabilsag",
            116
        ],
        [
            "Holy",
            18,
            "Apis",
            "/megaten-fusion-tool/smt4/demons/Apis",
            117
        ],
        [
            "Holy",
            3,
            "Heqet",
            "/megaten-fusion-tool/smt4/demons/Heqet",
            118
        ],
        [
            "Genma",
            73,
            "Heimdall",
            "/megaten-fusion-tool/smt4/demons/Heimdall",
            119
        ],
        [
            "Genma",
            66,
            "Hanuman",
            "/megaten-fusion-tool/smt4/demons/Hanuman",
            120
        ],
        [
            "Genma",
            61,
            "Jarilo",
            "/megaten-fusion-tool/smt4/demons/Jarilo",
            121
        ],
        [
            "Genma",
            56,
            "Kresnik",
            "/megaten-fusion-tool/smt4/demons/Kresnik",
            122
        ],
        [
            "Genma",
            50,
            "Cu Chulainn",
            "/megaten-fusion-tool/smt4/demons/Cu%20Chulainn",
            123
        ],
        [
            "Genma",
            44,
            "Kurama Tengu",
            "/megaten-fusion-tool/smt4/demons/Kurama%20Tengu",
            124
        ],
        [
            "Genma",
            39,
            "Tlaloc",
            "/megaten-fusion-tool/smt4/demons/Tlaloc",
            125
        ],
        [
            "Genma",
            34,
            "Frost Ace",
            "/megaten-fusion-tool/smt4/demons/Frost%20Ace",
            126
        ],
        [
            "Genma",
            29,
            "Baldur",
            "/megaten-fusion-tool/smt4/demons/Baldur",
            127
        ],
        [
            "Genma",
            24,
            "Nata Taishi",
            "/megaten-fusion-tool/smt4/demons/Nata%20Taishi",
            128
        ],
        [
            "Genma",
            18,
            "Ictinike",
            "/megaten-fusion-tool/smt4/demons/Ictinike",
            129
        ],
        [
            "Genma",
            13,
            "Tam Lin",
            "/megaten-fusion-tool/smt4/demons/Tam%20Lin",
            130
        ],
        [
            "Fairy",
            75,
            "Demonee-Ho",
            "/megaten-fusion-tool/smt4/demons/Demonee-Ho",
            131
        ],
        [
            "Fairy",
            70,
            "Titania",
            "/megaten-fusion-tool/smt4/demons/Titania",
            132
        ],
        [
            "Fairy",
            64,
            "Oberon",
            "/megaten-fusion-tool/smt4/demons/Oberon",
            133
        ],
        [
            "Fairy",
            58,
            "Vivian",
            "/megaten-fusion-tool/smt4/demons/Vivian",
            134
        ],
        [
            "Fairy",
            52,
            "Lorelei",
            "/megaten-fusion-tool/smt4/demons/Lorelei",
            135
        ],
        [
            "Fairy",
            47,
            "Nadja",
            "/megaten-fusion-tool/smt4/demons/Nadja",
            136
        ],
        [
            "Fairy",
            42,
            "Silky",
            "/megaten-fusion-tool/smt4/demons/Silky",
            137
        ],
        [
            "Fairy",
            36,
            "Kelpie",
            "/megaten-fusion-tool/smt4/demons/Kelpie",
            138
        ],
        [
            "Fairy",
            32,
            "Setanta",
            "/megaten-fusion-tool/smt4/demons/Setanta",
            139
        ],
        [
            "Fairy",
            28,
            "High Pixie",
            "/megaten-fusion-tool/smt4/demons/High%20Pixie",
            140
        ],
        [
            "Fairy",
            24,
            "Goblin",
            "/megaten-fusion-tool/smt4/demons/Goblin",
            141
        ],
        [
            "Fairy",
            19,
            "Pyro Jack",
            "/megaten-fusion-tool/smt4/demons/Pyro%20Jack",
            142
        ],
        [
            "Fairy",
            15,
            "Jack Frost",
            "/megaten-fusion-tool/smt4/demons/Jack%20Frost",
            143
        ],
        [
            "Fairy",
            11,
            "Spriggan",
            "/megaten-fusion-tool/smt4/demons/Spriggan",
            144
        ],
        [
            "Fairy",
            7,
            "Pixie",
            "/megaten-fusion-tool/smt4/demons/Pixie",
            145
        ],
        [
            "Fairy",
            2,
            "Napaea",
            "/megaten-fusion-tool/smt4/demons/Napaea",
            146
        ],
        [
            "Beast",
            72,
            "Cerberus",
            "/megaten-fusion-tool/smt4/demons/Cerberus",
            147
        ],
        [
            "Beast",
            65,
            "Ammut",
            "/megaten-fusion-tool/smt4/demons/Ammut",
            148
        ],
        [
            "Beast",
            57,
            "Orthrus",
            "/megaten-fusion-tool/smt4/demons/Orthrus",
            149
        ],
        [
            "Beast",
            49,
            "Dormarth",
            "/megaten-fusion-tool/smt4/demons/Dormarth",
            150
        ],
        [
            "Beast",
            43,
            "Hsing-Hsing",
            "/megaten-fusion-tool/smt4/demons/Hsing-Hsing",
            151
        ],
        [
            "Beast",
            37,
            "Nekomata",
            "/megaten-fusion-tool/smt4/demons/Nekomata",
            152
        ],
        [
            "Beast",
            33,
            "Minotaur",
            "/megaten-fusion-tool/smt4/demons/Minotaur",
            153
        ],
        [
            "Beast",
            31,
            "Hairy Jack",
            "/megaten-fusion-tool/smt4/demons/Hairy%20Jack",
            154
        ],
        [
            "Beast",
            25,
            "Inugami",
            "/megaten-fusion-tool/smt4/demons/Inugami",
            155
        ],
        [
            "Beast",
            19,
            "Kabuso",
            "/megaten-fusion-tool/smt4/demons/Kabuso",
            156
        ],
        [
            "Beast",
            13,
            "Kaso",
            "/megaten-fusion-tool/smt4/demons/Kaso",
            157
        ],
        [
            "Beast",
            8,
            "Stonka",
            "/megaten-fusion-tool/smt4/demons/Stonka",
            158
        ],
        [
            "Beast",
            3,
            "Gryphon",
            "/megaten-fusion-tool/smt4/demons/Gryphon",
            159
        ],
        [
            "Jirae",
            55,
            "Gogmagog",
            "/megaten-fusion-tool/smt4/demons/Gogmagog",
            160
        ],
        [
            "Jirae",
            46,
            "Tlaltecuhtli",
            "/megaten-fusion-tool/smt4/demons/Tlaltecuhtli",
            161
        ],
        [
            "Jirae",
            44,
            "Kuebiko",
            "/megaten-fusion-tool/smt4/demons/Kuebiko",
            162
        ],
        [
            "Jirae",
            37,
            "Titan",
            "/megaten-fusion-tool/smt4/demons/Titan",
            163
        ],
        [
            "Jirae",
            30,
            "Tsuchigumo",
            "/megaten-fusion-tool/smt4/demons/Tsuchigumo",
            164
        ],
        [
            "Jirae",
            24,
            "Kwancha",
            "/megaten-fusion-tool/smt4/demons/Kwancha",
            165
        ],
        [
            "Jirae",
            19,
            "Sudama",
            "/megaten-fusion-tool/smt4/demons/Sudama",
            166
        ],
        [
            "Jirae",
            14,
            "Hua Po",
            "/megaten-fusion-tool/smt4/demons/Hua%20Po",
            167
        ],
        [
            "Jirae",
            8,
            "Knocker",
            "/megaten-fusion-tool/smt4/demons/Knocker",
            168
        ],
        [
            "Jirae",
            4,
            "Dwarf",
            "/megaten-fusion-tool/smt4/demons/Dwarf",
            169
        ],
        [
            "Snake",
            72,
            "Ananta",
            "/megaten-fusion-tool/smt4/demons/Ananta",
            170
        ],
        [
            "Snake",
            66,
            "Pendragon",
            "/megaten-fusion-tool/smt4/demons/Pendragon",
            171
        ],
        [
            "Snake",
            60,
            "Orochi",
            "/megaten-fusion-tool/smt4/demons/Orochi",
            172
        ],
        [
            "Snake",
            49,
            "Ouroboros",
            "/megaten-fusion-tool/smt4/demons/Ouroboros",
            173
        ],
        [
            "Snake",
            42,
            "Gui Xian",
            "/megaten-fusion-tool/smt4/demons/Gui%20Xian",
            174
        ],
        [
            "Snake",
            33,
            "Yurlungur",
            "/megaten-fusion-tool/smt4/demons/Yurlungur",
            175
        ],
        [
            "Snake",
            26,
            "Vouivre",
            "/megaten-fusion-tool/smt4/demons/Vouivre",
            176
        ],
        [
            "Snake",
            18,
            "Nozuchi",
            "/megaten-fusion-tool/smt4/demons/Nozuchi",
            177
        ],
        [
            "Snake",
            11,
            "Naga",
            "/megaten-fusion-tool/smt4/demons/Naga",
            178
        ],
        [
            "Reaper",
            89,
            "Mot",
            "/megaten-fusion-tool/smt4/demons/Mot",
            179
        ],
        [
            "Reaper",
            82,
            "Nergal",
            "/megaten-fusion-tool/smt4/demons/Nergal",
            180
        ],
        [
            "Reaper",
            76,
            "Ixtab",
            "/megaten-fusion-tool/smt4/demons/Ixtab",
            181
        ],
        [
            "Reaper",
            70,
            "Cernunnos",
            "/megaten-fusion-tool/smt4/demons/Cernunnos",
            182
        ],
        [
            "Reaper",
            63,
            "Guedhe",
            "/megaten-fusion-tool/smt4/demons/Guedhe",
            183
        ],
        [
            "Reaper",
            57,
            "Persephone",
            "/megaten-fusion-tool/smt4/demons/Persephone",
            184
        ],
        [
            "Reaper",
            50,
            "Orcus",
            "/megaten-fusion-tool/smt4/demons/Orcus",
            185
        ],
        [
            "Reaper",
            44,
            "Hel",
            "/megaten-fusion-tool/smt4/demons/Hel",
            186
        ],
        [
            "Wilder",
            71,
            "Fenrir",
            "/megaten-fusion-tool/smt4/demons/Fenrir",
            187
        ],
        [
            "Wilder",
            65,
            "Taowu",
            "/megaten-fusion-tool/smt4/demons/Taowu",
            188
        ],
        [
            "Wilder",
            59,
            "Cabracan",
            "/megaten-fusion-tool/smt4/demons/Cabracan",
            189
        ],
        [
            "Wilder",
            52,
            "Catoblepas",
            "/megaten-fusion-tool/smt4/demons/Catoblepas",
            190
        ],
        [
            "Wilder",
            45,
            "Manticore",
            "/megaten-fusion-tool/smt4/demons/Manticore",
            191
        ],
        [
            "Wilder",
            39,
            "Porewit",
            "/megaten-fusion-tool/smt4/demons/Porewit",
            192
        ],
        [
            "Wilder",
            33,
            "Peallaidh",
            "/megaten-fusion-tool/smt4/demons/Peallaidh",
            193
        ],
        [
            "Wilder",
            26,
            "Nue",
            "/megaten-fusion-tool/smt4/demons/Nue",
            194
        ],
        [
            "Wilder",
            18,
            "Raijuu",
            "/megaten-fusion-tool/smt4/demons/Raijuu",
            195
        ],
        [
            "Wilder",
            12,
            "Jueyuan",
            "/megaten-fusion-tool/smt4/demons/Jueyuan",
            196
        ],
        [
            "Wilder",
            6,
            "Chagrin",
            "/megaten-fusion-tool/smt4/demons/Chagrin",
            197
        ],
        [
            "Jaki",
            70,
            "Hekatoncheires",
            "/megaten-fusion-tool/smt4/demons/Hekatoncheires",
            198
        ],
        [
            "Jaki",
            59,
            "Girimehkala",
            "/megaten-fusion-tool/smt4/demons/Girimehkala",
            199
        ],
        [
            "Jaki",
            50,
            "Grendel",
            "/megaten-fusion-tool/smt4/demons/Grendel",
            200
        ],
        [
            "Jaki",
            44,
            "Ogre",
            "/megaten-fusion-tool/smt4/demons/Ogre",
            201
        ],
        [
            "Jaki",
            38,
            "Rakshasa",
            "/megaten-fusion-tool/smt4/demons/Rakshasa",
            202
        ],
        [
            "Jaki",
            31,
            "Black Frost",
            "/megaten-fusion-tool/smt4/demons/Black%20Frost",
            203
        ],
        [
            "Jaki",
            25,
            "Wendigo",
            "/megaten-fusion-tool/smt4/demons/Wendigo",
            204
        ],
        [
            "Jaki",
            17,
            "Ippon-Datara",
            "/megaten-fusion-tool/smt4/demons/Ippon-Datara",
            205
        ],
        [
            "Jaki",
            10,
            "Gremlin",
            "/megaten-fusion-tool/smt4/demons/Gremlin",
            206
        ],
        [
            "Jaki",
            1,
            "Lham Dearg",
            "/megaten-fusion-tool/smt4/demons/Lham%20Dearg",
            207
        ],
        [
            "Vermin",
            40,
            "Arachne",
            "/megaten-fusion-tool/smt4/demons/Arachne",
            208
        ],
        [
            "Vermin",
            29,
            "Okiku-Mushi",
            "/megaten-fusion-tool/smt4/demons/Okiku-Mushi",
            209
        ],
        [
            "Vermin",
            22,
            "Ubu",
            "/megaten-fusion-tool/smt4/demons/Ubu",
            210
        ],
        [
            "Vermin",
            11,
            "Mothman",
            "/megaten-fusion-tool/smt4/demons/Mothman",
            211
        ],
        [
            "Vermin",
            3,
            "Myrmecolion",
            "/megaten-fusion-tool/smt4/demons/Myrmecolion",
            212
        ],
        [
            "Fury",
            90,
            "Shiva",
            "/megaten-fusion-tool/smt4/demons/Shiva",
            213
        ],
        [
            "Fury",
            88,
            "Susano-o",
            "/megaten-fusion-tool/smt4/demons/Susano-o",
            214
        ],
        [
            "Fury",
            80,
            "Kartikeya",
            "/megaten-fusion-tool/smt4/demons/Kartikeya",
            215
        ],
        [
            "Fury",
            73,
            "Masakado",
            "/megaten-fusion-tool/smt4/demons/Masakado",
            216
        ],
        [
            "Fury",
            64,
            "Beiji-Weng",
            "/megaten-fusion-tool/smt4/demons/Beiji-Weng",
            217
        ],
        [
            "Fury",
            57,
            "Wu Kong",
            "/megaten-fusion-tool/smt4/demons/Wu%20Kong",
            218
        ],
        [
            "Fury",
            50,
            "Chernobog",
            "/megaten-fusion-tool/smt4/demons/Chernobog",
            219
        ],
        [
            "Fury",
            43,
            "Asura",
            "/megaten-fusion-tool/smt4/demons/Asura",
            220
        ],
        [
            "Fury",
            37,
            "Tonatiuh",
            "/megaten-fusion-tool/smt4/demons/Tonatiuh",
            221
        ],
        [
            "Fury",
            31,
            "Ares",
            "/megaten-fusion-tool/smt4/demons/Ares",
            222
        ],
        [
            "Lady",
            79,
            "Xi Wangmu",
            "/megaten-fusion-tool/smt4/demons/Xi%20Wangmu",
            223
        ],
        [
            "Lady",
            73,
            "Skadi",
            "/megaten-fusion-tool/smt4/demons/Skadi",
            224
        ],
        [
            "Lady",
            64,
            "Black Maria",
            "/megaten-fusion-tool/smt4/demons/Black%20Maria",
            225
        ],
        [
            "Lady",
            58,
            "Isis",
            "/megaten-fusion-tool/smt4/demons/Isis",
            226
        ],
        [
            "Lady",
            51,
            "Asherah",
            "/megaten-fusion-tool/smt4/demons/Asherah",
            227
        ],
        [
            "Lady",
            42,
            "Diana",
            "/megaten-fusion-tool/smt4/demons/Diana",
            228
        ],
        [
            "Lady",
            36,
            "Hariti",
            "/megaten-fusion-tool/smt4/demons/Hariti",
            229
        ],
        [
            "Lady",
            27,
            "Sedna",
            "/megaten-fusion-tool/smt4/demons/Sedna",
            230
        ],
        [
            "Lady",
            17,
            "Dzelarhons",
            "/megaten-fusion-tool/smt4/demons/Dzelarhons",
            231
        ],
        [
            "Lady",
            6,
            "Pele",
            "/megaten-fusion-tool/smt4/demons/Pele",
            232
        ],
        [
            "Dragon",
            78,
            "Huang Long",
            "/megaten-fusion-tool/smt4/demons/Huang%20Long",
            233
        ],
        [
            "Dragon",
            75,
            "Koga Saburo",
            "/megaten-fusion-tool/smt4/demons/Koga%20Saburo",
            234
        ],
        [
            "Dragon",
            69,
            "Quetzalcoatl",
            "/megaten-fusion-tool/smt4/demons/Quetzalcoatl",
            235
        ],
        [
            "Dragon",
            60,
            "Zhu Yin",
            "/megaten-fusion-tool/smt4/demons/Zhu%20Yin",
            236
        ],
        [
            "Dragon",
            51,
            "Illuyanka",
            "/megaten-fusion-tool/smt4/demons/Illuyanka",
            237
        ],
        [
            "Dragon",
            41,
            "Long",
            "/megaten-fusion-tool/smt4/demons/Long",
            238
        ],
        [
            "Dragon",
            33,
            "Gucumatz",
            "/megaten-fusion-tool/smt4/demons/Gucumatz",
            239
        ],
        [
            "Dragon",
            23,
            "Patrimpas",
            "/megaten-fusion-tool/smt4/demons/Patrimpas",
            240
        ],
        [
            "Dragon",
            13,
            "Makara",
            "/megaten-fusion-tool/smt4/demons/Makara",
            241
        ],
        [
            "Kishin",
            76,
            "Thor",
            "/megaten-fusion-tool/smt4/demons/Thor",
            242
        ],
        [
            "Kishin",
            70,
            "Marici",
            "/megaten-fusion-tool/smt4/demons/Marici",
            243
        ],
        [
            "Kishin",
            64,
            "Bishamonten",
            "/megaten-fusion-tool/smt4/demons/Bishamonten",
            244
        ],
        [
            "Kishin",
            57,
            "Jikokuten",
            "/megaten-fusion-tool/smt4/demons/Jikokuten",
            245
        ],
        [
            "Kishin",
            50,
            "Zhong Kui",
            "/megaten-fusion-tool/smt4/demons/Zhong%20Kui",
            246
        ],
        [
            "Kishin",
            44,
            "Koumokuten",
            "/megaten-fusion-tool/smt4/demons/Koumokuten",
            247
        ],
        [
            "Kishin",
            37,
            "Zouchouten",
            "/megaten-fusion-tool/smt4/demons/Zouchouten",
            248
        ],
        [
            "Fallen",
            90,
            "Samael",
            "/megaten-fusion-tool/smt4/demons/Samael",
            249
        ],
        [
            "Fallen",
            83,
            "Botis",
            "/megaten-fusion-tool/smt4/demons/Botis",
            250
        ],
        [
            "Fallen",
            76,
            "Barbatos",
            "/megaten-fusion-tool/smt4/demons/Barbatos",
            251
        ],
        [
            "Fallen",
            69,
            "Shax",
            "/megaten-fusion-tool/smt4/demons/Shax",
            252
        ],
        [
            "Fallen",
            63,
            "Murmur",
            "/megaten-fusion-tool/smt4/demons/Murmur",
            253
        ],
        [
            "Fallen",
            58,
            "Gemori",
            "/megaten-fusion-tool/smt4/demons/Gemori",
            254
        ],
        [
            "Fallen",
            53,
            "Mitra",
            "/megaten-fusion-tool/smt4/demons/Mitra",
            255
        ],
        [
            "Fallen",
            48,
            "Decarabia",
            "/megaten-fusion-tool/smt4/demons/Decarabia",
            256
        ],
        [
            "Fallen",
            43,
            "Nebiros",
            "/megaten-fusion-tool/smt4/demons/Nebiros",
            257
        ],
        [
            "Fallen",
            38,
            "Ose",
            "/megaten-fusion-tool/smt4/demons/Ose",
            258
        ],
        [
            "Fallen",
            32,
            "Dantalian",
            "/megaten-fusion-tool/smt4/demons/Dantalian",
            259
        ],
        [
            "Fallen",
            26,
            "Orias",
            "/megaten-fusion-tool/smt4/demons/Orias",
            260
        ],
        [
            "Fallen",
            19,
            "Halphas",
            "/megaten-fusion-tool/smt4/demons/Halphas",
            261
        ],
        [
            "Fallen",
            12,
            "Bifrons",
            "/megaten-fusion-tool/smt4/demons/Bifrons",
            262
        ],
        [
            "Fallen",
            5,
            "Melchom",
            "/megaten-fusion-tool/smt4/demons/Melchom",
            263
        ],
        [
            "Brute",
            78,
            "Ongyo-Ki",
            "/megaten-fusion-tool/smt4/demons/Ongyo-Ki",
            264
        ],
        [
            "Brute",
            70,
            "Yaksha",
            "/megaten-fusion-tool/smt4/demons/Yaksha",
            265
        ],
        [
            "Brute",
            63,
            "Berserker",
            "/megaten-fusion-tool/smt4/demons/Berserker",
            266
        ],
        [
            "Brute",
            55,
            "Sui-Ki",
            "/megaten-fusion-tool/smt4/demons/Sui-Ki",
            267
        ],
        [
            "Brute",
            49,
            "Fuu-Ki",
            "/megaten-fusion-tool/smt4/demons/Fuu-Ki",
            268
        ],
        [
            "Brute",
            43,
            "Kin-Ki",
            "/megaten-fusion-tool/smt4/demons/Kin-Ki",
            269
        ],
        [
            "Brute",
            37,
            "Yomotsu-Ikusa",
            "/megaten-fusion-tool/smt4/demons/Yomotsu-Ikusa",
            270
        ],
        [
            "Brute",
            31,
            "Yamawaro",
            "/megaten-fusion-tool/smt4/demons/Yamawaro",
            271
        ],
        [
            "Brute",
            25,
            "Momunofu",
            "/megaten-fusion-tool/smt4/demons/Momunofu",
            272
        ],
        [
            "Brute",
            19,
            "Azumi",
            "/megaten-fusion-tool/smt4/demons/Azumi",
            273
        ],
        [
            "Brute",
            13,
            "Oni",
            "/megaten-fusion-tool/smt4/demons/Oni",
            274
        ],
        [
            "Brute",
            7,
            "Bilwis",
            "/megaten-fusion-tool/smt4/demons/Bilwis",
            275
        ],
        [
            "Femme",
            75,
            "Kali",
            "/megaten-fusion-tool/smt4/demons/Kali",
            276
        ],
        [
            "Femme",
            68,
            "Rangda",
            "/megaten-fusion-tool/smt4/demons/Rangda",
            277
        ],
        [
            "Femme",
            62,
            "Dakini",
            "/megaten-fusion-tool/smt4/demons/Dakini",
            278
        ],
        [
            "Femme",
            56,
            "Taraka",
            "/megaten-fusion-tool/smt4/demons/Taraka",
            279
        ],
        [
            "Femme",
            49,
            "Atropos",
            "/megaten-fusion-tool/smt4/demons/Atropos",
            280
        ],
        [
            "Femme",
            43,
            "Lachesis",
            "/megaten-fusion-tool/smt4/demons/Lachesis",
            281
        ],
        [
            "Femme",
            37,
            "Clotho",
            "/megaten-fusion-tool/smt4/demons/Clotho",
            282
        ],
        [
            "Femme",
            35,
            "Medusa",
            "/megaten-fusion-tool/smt4/demons/Medusa",
            283
        ],
        [
            "Femme",
            29,
            "Yuki Jyorou",
            "/megaten-fusion-tool/smt4/demons/Yuki%20Jyorou",
            284
        ],
        [
            "Femme",
            23,
            "Shikome",
            "/megaten-fusion-tool/smt4/demons/Shikome",
            285
        ],
        [
            "Femme",
            17,
            "Strix",
            "/megaten-fusion-tool/smt4/demons/Strix",
            286
        ],
        [
            "Femme",
            11,
            "Leanan Sidhe",
            "/megaten-fusion-tool/smt4/demons/Leanan%20Sidhe",
            287
        ],
        [
            "Night",
            77,
            "Maya",
            "/megaten-fusion-tool/smt4/demons/Maya",
            288
        ],
        [
            "Night",
            71,
            "Lilith",
            "/megaten-fusion-tool/smt4/demons/Lilith",
            289
        ],
        [
            "Night",
            59,
            "Queen Mab",
            "/megaten-fusion-tool/smt4/demons/Queen%20Mab",
            290
        ],
        [
            "Night",
            53,
            "Wild Hunt",
            "/megaten-fusion-tool/smt4/demons/Wild%20Hunt",
            291
        ],
        [
            "Night",
            47,
            "Succubus",
            "/megaten-fusion-tool/smt4/demons/Succubus",
            292
        ],
        [
            "Night",
            40,
            "Kaiwan",
            "/megaten-fusion-tool/smt4/demons/Kaiwan",
            293
        ],
        [
            "Night",
            33,
            "Lilim",
            "/megaten-fusion-tool/smt4/demons/Lilim",
            294
        ],
        [
            "Night",
            28,
            "Incubus",
            "/megaten-fusion-tool/smt4/demons/Incubus",
            295
        ],
        [
            "Night",
            20,
            "Kikimora",
            "/megaten-fusion-tool/smt4/demons/Kikimora",
            296
        ],
        [
            "Night",
            14,
            "Sandman",
            "/megaten-fusion-tool/smt4/demons/Sandman",
            297
        ],
        [
            "Night",
            7,
            "Fomorian",
            "/megaten-fusion-tool/smt4/demons/Fomorian",
            298
        ],
        [
            "Night",
            2,
            "Mokoi",
            "/megaten-fusion-tool/smt4/demons/Mokoi",
            299
        ],
        [
            "Tyrant",
            94,
            "Mara",
            "/megaten-fusion-tool/smt4/demons/Mara",
            300
        ],
        [
            "Tyrant",
            92,
            "Lucifuge",
            "/megaten-fusion-tool/smt4/demons/Lucifuge",
            301
        ],
        [
            "Tyrant",
            87,
            "Chi You",
            "/megaten-fusion-tool/smt4/demons/Chi%20You",
            302
        ],
        [
            "Tyrant",
            81,
            "Surt",
            "/megaten-fusion-tool/smt4/demons/Surt",
            303
        ],
        [
            "Tyrant",
            75,
            "Tzitzimitl",
            "/megaten-fusion-tool/smt4/demons/Tzitzimitl",
            304
        ],
        [
            "Tyrant",
            70,
            "Beelzebub",
            "/megaten-fusion-tool/smt4/demons/Beelzebub",
            305
        ],
        [
            "Tyrant",
            69,
            "Azazel",
            "/megaten-fusion-tool/smt4/demons/Azazel",
            306
        ],
        [
            "Tyrant",
            64,
            "Abaddon",
            "/megaten-fusion-tool/smt4/demons/Abaddon",
            307
        ],
        [
            "Tyrant",
            58,
            "Loki",
            "/megaten-fusion-tool/smt4/demons/Loki",
            308
        ],
        [
            "Tyrant",
            53,
            "Belial",
            "/megaten-fusion-tool/smt4/demons/Belial",
            309
        ],
        [
            "Tyrant",
            51,
            "Asmodeus",
            "/megaten-fusion-tool/smt4/demons/Asmodeus",
            310
        ],
        [
            "Tyrant",
            48,
            "Astaroth",
            "/megaten-fusion-tool/smt4/demons/Astaroth",
            311
        ],
        [
            "Tyrant",
            42,
            "Balor",
            "/megaten-fusion-tool/smt4/demons/Balor",
            312
        ],
        [
            "Tyrant",
            37,
            "King Frost",
            "/megaten-fusion-tool/smt4/demons/King%20Frost",
            313
        ],
        [
            "Tyrant",
            32,
            "Samyaza",
            "/megaten-fusion-tool/smt4/demons/Samyaza",
            314
        ],
        [
            "Tyrant",
            27,
            "Horkos",
            "/megaten-fusion-tool/smt4/demons/Horkos",
            315
        ],
        [
            "Tyrant",
            21,
            "Mithras",
            "/megaten-fusion-tool/smt4/demons/Mithras",
            316
        ],
        [
            "Tyrant",
            15,
            "Morax",
            "/megaten-fusion-tool/smt4/demons/Morax",
            317
        ],
        [
            "Drake",
            86,
            "Vasuki",
            "/megaten-fusion-tool/smt4/demons/Vasuki",
            318
        ],
        [
            "Drake",
            81,
            "Python",
            "/megaten-fusion-tool/smt4/demons/Python",
            319
        ],
        [
            "Drake",
            74,
            "Fafnir",
            "/megaten-fusion-tool/smt4/demons/Fafnir",
            320
        ],
        [
            "Drake",
            68,
            "Ym",
            "/megaten-fusion-tool/smt4/demons/Ym",
            321
        ],
        [
            "Drake",
            62,
            "Niddhoggr",
            "/megaten-fusion-tool/smt4/demons/Niddhoggr",
            322
        ],
        [
            "Drake",
            55,
            "Tiamat",
            "/megaten-fusion-tool/smt4/demons/Tiamat",
            323
        ],
        [
            "Drake",
            47,
            "Mushussu",
            "/megaten-fusion-tool/smt4/demons/Mushussu",
            324
        ],
        [
            "Drake",
            39,
            "Kingu",
            "/megaten-fusion-tool/smt4/demons/Kingu",
            325
        ],
        [
            "Drake",
            30,
            "Basilisk",
            "/megaten-fusion-tool/smt4/demons/Basilisk",
            326
        ],
        [
            "Drake",
            23,
            "Bai Suzhen",
            "/megaten-fusion-tool/smt4/demons/Bai%20Suzhen",
            327
        ],
        [
            "Drake",
            15,
            "Toubyou",
            "/megaten-fusion-tool/smt4/demons/Toubyou",
            328
        ],
        [
            "Drake",
            9,
            "Zhu Tun She",
            "/megaten-fusion-tool/smt4/demons/Zhu%20Tun%20She",
            329
        ],
        [
            "Spirit",
            54,
            "Garrote",
            "/megaten-fusion-tool/smt4/demons/Garrote",
            330
        ],
        [
            "Spirit",
            47,
            "Legion",
            "/megaten-fusion-tool/smt4/demons/Legion",
            331
        ],
        [
            "Spirit",
            38,
            "Pisaca",
            "/megaten-fusion-tool/smt4/demons/Pisaca",
            332
        ],
        [
            "Spirit",
            31,
            "Inferno",
            "/megaten-fusion-tool/smt4/demons/Inferno",
            333
        ],
        [
            "Spirit",
            25,
            "Macabre",
            "/megaten-fusion-tool/smt4/demons/Macabre",
            334
        ],
        [
            "Spirit",
            19,
            "Quicksilver",
            "/megaten-fusion-tool/smt4/demons/Quicksilver",
            335
        ],
        [
            "Spirit",
            13,
            "Poltergeist",
            "/megaten-fusion-tool/smt4/demons/Poltergeist",
            336
        ],
        [
            "Spirit",
            8,
            "Wicker Man",
            "/megaten-fusion-tool/smt4/demons/Wicker%20Man",
            337
        ],
        [
            "Spirit",
            4,
            "Dybbuk",
            "/megaten-fusion-tool/smt4/demons/Dybbuk",
            338
        ],
        [
            "Foul",
            40,
            "Mad Gasser",
            "/megaten-fusion-tool/smt4/demons/Mad%20Gasser",
            339
        ],
        [
            "Foul",
            25,
            "Tattooed Man",
            "/megaten-fusion-tool/smt4/demons/Tattooed%20Man",
            340
        ],
        [
            "Foul",
            23,
            "Night Stalker",
            "/megaten-fusion-tool/smt4/demons/Night%20Stalker",
            341
        ],
        [
            "Foul",
            16,
            "Hooligan",
            "/megaten-fusion-tool/smt4/demons/Hooligan",
            342
        ],
        [
            "Foul",
            9,
            "Jack the Ripper",
            "/megaten-fusion-tool/smt4/demons/Jack%20the%20Ripper",
            343
        ],
        [
            "Foul",
            2,
            "Slime",
            "/megaten-fusion-tool/smt4/demons/Slime",
            344
        ],
        [
            "Ghost",
            74,
            "Vetala",
            "/megaten-fusion-tool/smt4/demons/Vetala",
            345
        ],
        [
            "Ghost",
            67,
            "Dullahan",
            "/megaten-fusion-tool/smt4/demons/Dullahan",
            346
        ],
        [
            "Ghost",
            58,
            "Kudlak",
            "/megaten-fusion-tool/smt4/demons/Kudlak",
            347
        ],
        [
            "Ghost",
            49,
            "Ghoul",
            "/megaten-fusion-tool/smt4/demons/Ghoul",
            348
        ],
        [
            "Ghost",
            40,
            "Enku",
            "/megaten-fusion-tool/smt4/demons/Enku",
            349
        ],
        [
            "Ghost",
            32,
            "Churel",
            "/megaten-fusion-tool/smt4/demons/Churel",
            350
        ],
        [
            "Ghost",
            24,
            "Mou-Ryo",
            "/megaten-fusion-tool/smt4/demons/Mou-Ryo",
            351
        ],
        [
            "Ghost",
            18,
            "Obariyon",
            "/megaten-fusion-tool/smt4/demons/Obariyon",
            352
        ],
        [
            "Ghost",
            12,
            "Preta",
            "/megaten-fusion-tool/smt4/demons/Preta",
            353
        ],
        [
            "Ghost",
            6,
            "Strigoii",
            "/megaten-fusion-tool/smt4/demons/Strigoii",
            354
        ],
        [
            "Fiend",
            93,
            "Mother Harlot",
            "/megaten-fusion-tool/smt4/demons/Mother%20Harlot",
            355
        ],
        [
            "Fiend",
            91,
            "Trumpeter",
            "/megaten-fusion-tool/smt4/demons/Trumpeter",
            356
        ],
        [
            "Fiend",
            89,
            "Pale Rider",
            "/megaten-fusion-tool/smt4/demons/Pale%20Rider",
            357
        ],
        [
            "Fiend",
            88,
            "Black Rider",
            "/megaten-fusion-tool/smt4/demons/Black%20Rider",
            358
        ],
        [
            "Fiend",
            87,
            "Red Rider",
            "/megaten-fusion-tool/smt4/demons/Red%20Rider",
            359
        ],
        [
            "Fiend",
            86,
            "White Rider",
            "/megaten-fusion-tool/smt4/demons/White%20Rider",
            360
        ],
        [
            "Fiend",
            84,
            "Matador",
            "/megaten-fusion-tool/smt4/demons/Matador",
            361
        ],
        [
            "Fiend",
            83,
            "Chemtrail",
            "/megaten-fusion-tool/smt4/demons/Chemtrail",
            362
        ],
        [
            "Fiend",
            22,
            "David",
            "/megaten-fusion-tool/smt4/demons/David",
            363
        ],
        [
            "Enigma",
            80,
            "Kangiten",
            "/megaten-fusion-tool/smt4/demons/Kangiten",
            364
        ],
        [
            "Enigma",
            72,
            "Kama",
            "/megaten-fusion-tool/smt4/demons/Kama",
            365
        ],
        [
            "Enigma",
            60,
            "Kinmamon",
            "/megaten-fusion-tool/smt4/demons/Kinmamon",
            366
        ],
        [
            "Enigma",
            42,
            "Futotama",
            "/megaten-fusion-tool/smt4/demons/Futotama",
            367
        ],
        [
            "Enigma",
            27,
            "Kanbari",
            "/megaten-fusion-tool/smt4/demons/Kanbari",
            368
        ],
        [
            "Food",
            38,
            "Hare of Inaba",
            "/megaten-fusion-tool/smt4/demons/Hare%20of%20Inaba",
            369
        ],
        [
            "Food",
            28,
            "Kuda",
            "/megaten-fusion-tool/smt4/demons/Kuda",
            370
        ],
        [
            "Food",
            21,
            "Chupacabra",
            "/megaten-fusion-tool/smt4/demons/Chupacabra",
            371
        ],
        [
            "Food",
            15,
            "Mamedanuki",
            "/megaten-fusion-tool/smt4/demons/Mamedanuki",
            372
        ],
        [
            "Food",
            9,
            "Katakirauwa",
            "/megaten-fusion-tool/smt4/demons/Katakirauwa",
            373
        ],
        [
            "Food",
            3,
            "Onmoraki",
            "/megaten-fusion-tool/smt4/demons/Onmoraki",
            374
        ],
        [
            "Zealot",
            82,
            "Tezcatlipoca",
            "/megaten-fusion-tool/smt4/demons/Tezcatlipoca",
            375
        ],
        [
            "Zealot",
            73,
            "Attis",
            "/megaten-fusion-tool/smt4/demons/Attis",
            376
        ],
        [
            "Zealot",
            58,
            "Aramisaki",
            "/megaten-fusion-tool/smt4/demons/Aramisaki",
            377
        ],
        [
            "Zealot",
            41,
            "Dionysus",
            "/megaten-fusion-tool/smt4/demons/Dionysus",
            378
        ],
        [
            "Zealot",
            24,
            "Ogun",
            "/megaten-fusion-tool/smt4/demons/Ogun",
            379
        ],
        [
            "Entity",
            84,
            "Alilat",
            "/megaten-fusion-tool/smt4/demons/Alilat",
            380
        ],
        [
            "Famed",
            90,
            "Yamato-Takeru",
            "/megaten-fusion-tool/smt4/demons/Yamato-Takeru",
            381
        ],
        [
            "Famed",
            86,
            "Huang Di",
            "/megaten-fusion-tool/smt4/demons/Huang%20Di",
            382
        ],
        [
            "Famed",
            84,
            "Michizane",
            "/megaten-fusion-tool/smt4/demons/Michizane",
            383
        ],
        [
            "Famed",
            80,
            "Tokisada",
            "/megaten-fusion-tool/smt4/demons/Tokisada",
            384
        ],
        [
            "Famed",
            77,
            "Tenkai",
            "/megaten-fusion-tool/smt4/demons/Tenkai",
            385
        ],
        [
            "Famed",
            74,
            "Rama",
            "/megaten-fusion-tool/smt4/demons/Rama",
            386
        ],
        [
            "Famed",
            67,
            "Kanseiteikun",
            "/megaten-fusion-tool/smt4/demons/Kanseiteikun",
            387
        ],
        [
            "Famed",
            61,
            "Siegfried",
            "/megaten-fusion-tool/smt4/demons/Siegfried",
            388
        ],
        [
            "Famed",
            55,
            "Hagen",
            "/megaten-fusion-tool/smt4/demons/Hagen",
            389
        ],
        [
            "Famed",
            49,
            "Jeanne D'Arc",
            "/megaten-fusion-tool/smt4/demons/Jeanne%20D'Arc",
            390
        ],
        [
            "Famed",
            43,
            "Lanling Wang",
            "/megaten-fusion-tool/smt4/demons/Lanling%20Wang",
            391
        ],
        [
            "Famed",
            36,
            "Yoshitsune",
            "/megaten-fusion-tool/smt4/demons/Yoshitsune",
            392
        ],
        [
            "Amatsu",
            82,
            "Omoikane",
            "/megaten-fusion-tool/smt4/demons/Omoikane",
            393
        ],
        [
            "Amatsu",
            79,
            "Amaterasu",
            "/megaten-fusion-tool/smt4/demons/Amaterasu",
            394
        ],
        [
            "Amatsu",
            55,
            "Take-Mikazuchi",
            "/megaten-fusion-tool/smt4/demons/Take-Mikazuchi",
            395
        ],
        [
            "Amatsu",
            22,
            "Ame no Uzume",
            "/megaten-fusion-tool/smt4/demons/Ame%20no%20Uzume",
            396
        ],
        [
            "Kunitsu",
            65,
            "Oumitsunu",
            "/megaten-fusion-tool/smt4/demons/Oumitsunu",
            397
        ],
        [
            "Kunitsu",
            57,
            "Arahabaki",
            "/megaten-fusion-tool/smt4/demons/Arahabaki",
            398
        ],
        [
            "Kunitsu",
            49,
            "Hitokoto-Nushi",
            "/megaten-fusion-tool/smt4/demons/Hitokoto-Nushi",
            399
        ],
        [
            "Kunitsu",
            41,
            "Kushinada-Hime",
            "/megaten-fusion-tool/smt4/demons/Kushinada-Hime",
            400
        ],
        [
            "Kunitsu",
            34,
            "Okuninushi",
            "/megaten-fusion-tool/smt4/demons/Okuninushi",
            401
        ],
        [
            "Kunitsu",
            21,
            "Take-Minakata",
            "/megaten-fusion-tool/smt4/demons/Take-Minakata",
            402
        ],
        [
            "Undead",
            49,
            "Alice",
            "/megaten-fusion-tool/smt4/demons/Alice",
            403
        ],
        [
            "Undead",
            44,
            "Patriot",
            "/megaten-fusion-tool/smt4/demons/Patriot",
            404
        ],
        [
            "Undead",
            35,
            "Corpses",
            "/megaten-fusion-tool/smt4/demons/Corpses",
            405
        ],
        [
            "Undead",
            17,
            "Zombie Cop",
            "/megaten-fusion-tool/smt4/demons/Zombie%20Cop",
            406
        ],
        [
            "Element",
            36,
            "Salamander",
            "/megaten-fusion-tool/smt4/demons/Salamander",
            407
        ],
        [
            "Element",
            32,
            "Undine",
            "/megaten-fusion-tool/smt4/demons/Undine",
            408
        ],
        [
            "Element",
            28,
            "Sylph",
            "/megaten-fusion-tool/smt4/demons/Sylph",
            409
        ],
        [
            "Element",
            24,
            "Gnome",
            "/megaten-fusion-tool/smt4/demons/Gnome",
            410
        ],
        [
            "Element",
            20,
            "Flaemis",
            "/megaten-fusion-tool/smt4/demons/Flaemis",
            411
        ],
        [
            "Element",
            16,
            "Aquans",
            "/megaten-fusion-tool/smt4/demons/Aquans",
            412
        ],
        [
            "Element",
            12,
            "Aeros",
            "/megaten-fusion-tool/smt4/demons/Aeros",
            413
        ],
        [
            "Element",
            8,
            "Erthys",
            "/megaten-fusion-tool/smt4/demons/Erthys",
            414
        ]
    ];

const storageSetter = () => {
    if (!localStorage.getItem("demon-list") && localStorage.getItem("demon-list") !== null){
        localStorage.setItem("demon-list", JSON.stringify(Array(415).fill(true)))
    }
    return JSON.parse(localStorage.getItem("demon-list") || '{}')

}

const useSortBy = () => {
    const [sortBy, setSortBy] = useState("default");
    const switchSortBy = useCallback((newValue: string) => {
        setSortBy((currentValue) => {
            if ((newValue === currentValue.slice(0, 4)) && (currentValue.slice(-3) === "des")){
                return newValue + "-asc"
            } else {
                return newValue + "-des"
            }
        })
    }, []);
    return { sortBy, switchSortBy };
}

interface CustomSortedProps {
    usable: boolean[],
    sortby: string,
    hide: boolean
}

const CustomSorted: FunctionComponent<CustomSortedProps> = ({usable, sortby, hide}) => {
    let el = 4, rev = false;

    switch (sortby) {
        case "name-asc":
            el = 2;
            rev = false;
            break
        case "name-des":
            el = 2;
            rev = true;
            break
        case "race-asc":
            el = 0;
            rev = false;
            break
        case "race-des":
            el = 0;
            rev = true;
            break
        case "levl-asc":
            el = 1;
            rev = true;
            break
        case "levl-des":
            el = 1;
            rev = false;
            break
        default:
            el = 4;
            rev = false;
    }

    let res = [...demonArr]
            .sort((a, b) => {
                const f = a[el], l = b[el];
                if ((el === 2) || (el === 0)){
                    if (f < l) {
                        return 1;
                    }
                    if (f > l) {
                        return -1;
                    }
                    return 0;
                } else if (typeof f === "number" && typeof l === "number"){
                    return f - l
                }
                return 0
            })

    rev ? res.reverse() : true;

    return (
        <>
            {
                res
                    .map((e, i) => {
                        return (
                            <TableRow
                                key={e[4]}
                                race={e[0]}
                                lvl={e[1]}
                                name={e[2]}
                                link={e[3]}
                                usable={usable[i]}
                                i={e[4]}
                                hide={hide}
                            />
                        )
                    })
            }
        </>
    )
}

export const DemonTable = () => {
    const usableArr: boolean[] = storageSetter();
    const {sortBy, switchSortBy} = useSortBy();
    const [hide, setHide] = useState(false);

    return (
        <>
            <div className={styles.logoContainer}>
                <img className={styles.logo} alt={"logo"} src={logo}/>
            </div>
            <div className={styles.tableBlock}>
                <Table striped bordered hover variant={"dark"}>
                    <thead className={styles.stickyHeader}>
                    <tr><th className={styles.headerBorderTop} colSpan={6}></th></tr>
                    <tr>
                        <th>
                            <button
                                onClick={() => {switchSortBy("race")}}
                                className={`${styles.sortBtn}
                                 ${
                                    sortBy === "race-asc" ? styles.down
                                        : sortBy === "race-des" ? styles.up : ""
                                }`}
                            >
                                Race
                            </button>
                        </th>
                        <th>
                            <button
                                onClick={() => {switchSortBy("levl")}}
                                className={`${styles.sortBtn}
                                 ${
                                    sortBy === "levl-asc" ? styles.down
                                        : sortBy === "levl-des" ? styles.up : ""
                                }`}
                            >
                                Level
                            </button>
                        </th>
                        <th>
                            <button
                                onClick={() => {switchSortBy("name")}}
                                className={`${styles.sortBtn}
                                 ${
                                    sortBy === "name-asc" ? styles.down
                                        : sortBy === "name-des" ? styles.up : ""
                                }`}
                            >
                                Name
                            </button>
                        </th>
                        <th>
                            <button
                                onClick={() => {setHide(!hide)}}
                                className={`${styles.sortBtn} ${styles.hidden}`}
                            >
                                Eliminated
                            </button>
                        </th>
                    </tr>
                    <tr><th className={styles.headerBorder} colSpan={6}></th></tr>
                    </thead>
                    <tbody className={styles.demonTableBody}>
                        <CustomSorted
                            usable={usableArr}
                            sortby={sortBy}
                            hide={hide}
                        />
                    </tbody>
                </Table>
            </div>
        </>
    )
}